// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA94m1jS3pDI0a_MixH-g5Pnhs-G_ukMac',
    appId: '1:194531693001:web:32491e96587d776ac55818',
    messagingSenderId: '194531693001',
    projectId: 'travelbuddyflutter-7061f',
    authDomain: 'travelbuddyflutter-7061f.firebaseapp.com',
    storageBucket: 'travelbuddyflutter-7061f.firebasestorage.app',
    measurementId: 'G-B93BLCZ6M2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbmiq5-4tJMtl1cIQZqiCWIlr9Ukeyw24',
    appId: '1:194531693001:android:eb3077d81b591c79c55818',
    messagingSenderId: '194531693001',
    projectId: 'travelbuddyflutter-7061f',
    storageBucket: 'travelbuddyflutter-7061f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHbyz-JSBkRaa_50wtuLAl1fZwvujGYZs',
    appId: '1:194531693001:ios:a3f14cddcffd15f9c55818',
    messagingSenderId: '194531693001',
    projectId: 'travelbuddyflutter-7061f',
    storageBucket: 'travelbuddyflutter-7061f.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectsTest',
  );
}
